// Mapa departamentos -> municipios (limpio y en formato objeto)
export const municipalitiesByDept = {
    Boaco: [
        "Boaco",
        "Camoapa",
        "San José de los Remates",
        "San Lorenzo",
        "Santa Lucía",
        "Teustepe",
    ],
    Carazo: [
        "Diriamba",
        "Dolores",
        "El Rosario",
        "Jinotepe",
        "La Conquista",
        "La Paz de Carazo",
        "San Marcos",
        "Santa Teresa",
    ],
    Chinandega: [
        "Chinandega",
        "Chichigalpa",
        "Cinco Pinos",
        "Corinto",
        "El Realejo",
        "El Viejo",
        "Posoltega",
        "Puerto Morazán",
        "Somotillo",
    ],
    Chontales: [
        "Acoyapa",
        "Comalapa",
        "Cuapa",
        "Juigalpa",
        "La Libertad",
        "San Pedro de Lóvago",
        "San Francisco de Cuapa",
        "Santa Lucía",
        "Santo Domingo",
        "Santo Tomás",
    ],
    "Costa Caribe Norte (RACCN)": [
        "Puerto Cabezas",
        "Waspam",
        "Siuna",
        "Bonanza",
        "Mulukukú",
    ],
    "Costa Caribe Sur (RACCS)": [
        "Bluefields",
        "Corn Island",
        "El Rama",
        "Laguna de Perlas",
        "Muelle de los Bueyes",
        "Nueva Guinea",
    ],
    Estelí: [
        "Estelí",
        "Condega",
        "La Trinidad",
        "Pueblo Nuevo",
        "San Juan de Limay",
        "San Nicolás",
    ],
    Granada: ["Granada", "Diriomo", "Nandaime", "Potosí", "Diria"],
    Jinotega: [
        "Jinotega",
        "El Cuá–Bosawa",
        "La Concordia",
        "San José de Bocay",
        "San Rafael del Norte",
        "Wiwilí de Jinotega",
        "Yalí",
    ],
    León: [
        "León",
        "Nagarote",
        "La Paz Centro",
        "Telica",
        "El Jicaral",
        "Santa Rosa del Peñón",
    ],
    Madriz: [
        "Somoto",
        "San Juan de Río Coco",
        "Palacagüina",
        "Las Sabanas",
        "San José de Cusmapa",
    ],
    Managua: [
        "Managua",
        "Ciudad Sandino",
        "El Crucero",
        "Mateare",
        "San Rafael del Sur",
        "San Francisco Libre",
        "Ticuantepe",
        "Villa El Carmen",
    ],
    Masaya: [
        "Masaya",
        "Nindirí",
        "Niquinohomo",
        "La Concepción",
        "San Juan de Oriente",
        "Tisma",
    ],
    Matagalpa: [
        "Matagalpa",
        "Ciudad Darío",
        "Esquipulas",
        "Matiguás",
        "Muy Muy",
        "San Isidro",
        "San Ramón",
    ],
    "Nueva Segovia": [
        "Ocotal",
        "Dipilto",
        "Jalapa",
        "Macuelizo",
        "Mozonte",
        "Quilalí",
        "San Fernando",
        "Santa María",
        "Wiwilí de Nueva Segovia",
    ],
    "Río San Juan": [
        "San Carlos",
        "El Almendro",
        "El Castillo",
        "Greytown (San Juan de Nicaragua)",
        "Morrito",
    ],
    Rivas: ["Rivas", "Potosí", "San Jorge", "San Juan del Sur", "Buenos Aires"],
};

export const departments = Object.keys(municipalitiesByDept);
